### ISSUE TITLE
Check for JDBC driver updates

### ISSUE THREAD

**Issue by AB-xdev** [xdev-software/xapi-db-mssql-2012#5]
The currently used mssql JDBC driver is relatively old.
We have projects that use forked versions with newer JDBC drivers.

Todo: 
* Check if we can update the JDBC drivers

**Comment by DanielLeinberger** [comment]
According to this [support matrix](https://learn.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16#java-and-jdbc-specification-support), we should be able to update to the newest jdbc driver [11.2.3](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/11.2.3.jre8).

There are, however, some downsides to this.
We are currently using [sqljdbc4 v4.0](https://mvnrepository.com/artifact/com.microsoft.sqlserver/sqljdbc4/4.0). This Dependency, according to the linked website, has no CVEs. 
Looking in the [support matrix](https://learn.microsoft.com/en-us/sql/connect/jdbc/microsoft-jdbc-driver-for-sql-server-support-matrix?view=sql-server-ver16#java-and-jdbc-specification-support), we can see, that v4.0 was made for JRE 1.5, 1.6 and 1.7 (We, however, compiled the code with 1.8, therefore it seems that this is also fine). The API-Version for this is 3.0 and 4.0.

A quick test shows, that there is no problem, whatsoever in upgrading to 11.2.3.jre8 due to the fact, that we are not using anything special things in the API. It looks like the supported API of 11.2.3.jre8 is down gradable to API 4.0.
However the supported JREs are newer. If we upgrade to the newest version this adapter loses the support of JRE 1.5 to 1.7.
There is also a [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-45868) listed in that newer version.

I'll make a pull request for version [11.2.3](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/11.2.3.jre8). We should discuss this update, however, in more detail.
